### ISSUE TITLE
 Is there any disconnection and reconnection? 有断线重连吗

### ISSUE THREAD

**Issue by a982246809** [adoontheway/nano-client-ts#2]
Is there any disconnection and reconnection? 有断线重连吗

**Comment by a982246809** [comment]
I want to use it in a vue project. Can it be used?
我想在vue项目中使用可以吗?

**Comment by adoontheway** [comment]
1. vue不能直接使用，需要做一些改动，比如：去掉一些cocos的类，替换成js原生的，这个你自己拉个分支就，花几分钟就可以搞定
2. 有支持重连，具体逻辑参考`nano.ts` line-170

**Comment by adoontheway** [comment]
这里有原生的websocket-js版本: [nano-websocket-client](https://github.com/nano-ecosystem/nano-websocket-client)
我做的这个版本就是根据这个nano js版本改来的

**Comment by a982246809** [comment]
[nano-websocket-client](https://github.com/nano-ecosystem/nano-websocket-client)它这个断线 有问题

**Comment by a982246809** [comment]
断线久了  就连回来了

**Comment by a982246809** [comment]
我草  reconnect竟然默认是false
